2025-07-15 05:30:08,027 - INFO - app.core.security - LOGIN: user_id=11, email=cursordemo3@gmail.com, user_type=demo, time=2025-07-15T12:30:08.027197
2025-07-15 05:30:56,318 - INFO - app.core.security - LOGOUT: user_id=11, email=cursordemo3@gmail.com, user_type=demo, time=2025-07-15T12:30:56.318548
2025-07-15 05:30:58,717 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-15T12:30:58.717083
2025-07-15 21:10:38,613 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 21:10:38,655 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 22:56:38,930 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-16T05:56:38.930752
2025-07-15 22:56:44,589 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-16T05:56:44.589355
2025-07-15 23:42:15,159 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 23:42:15,177 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 00:20:23,010 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-16T07:20:23.010462
2025-07-16 01:49:19,584 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 01:49:19,613 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 02:50:56,788 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-16T09:50:56.788622
2025-07-16 04:27:32,360 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-16T11:27:32.360562
2025-07-16 05:04:59,506 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-16T12:04:59.506214
2025-07-16 05:40:53,966 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-16T12:40:53.966168
2025-07-16 05:42:04,073 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-16T12:42:04.073444
2025-07-16 05:42:49,239 - INFO - app.core.security - LOGIN: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-16T12:42:49.239576
2025-07-16 05:43:33,935 - INFO - app.core.security - LOGOUT: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-16T12:43:33.935232
2025-07-16 05:43:35,809 - INFO - app.core.security - LOGIN: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-16T12:43:35.809518
2025-07-16 05:45:25,538 - INFO - app.core.security - LOGOUT: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-16T12:45:25.538078
2025-07-16 05:45:37,086 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-16T12:45:37.086577
2025-07-16 23:14:55,444 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 23:14:55,480 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 23:15:02,102 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T06:15:02.102792
2025-07-16 23:47:31,183 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T06:47:31.183829
2025-07-16 23:47:38,364 - INFO - app.core.security - LOGIN: user_id=11, email=root9678@gmail.com, user_type=live, time=2025-07-17T06:47:38.364280
2025-07-17 02:33:38,016 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 02:33:38,020 - WARNING - app.core.security - [Redis] AOF persistence not enabled. Enabling now...
2025-07-17 02:33:38,028 - INFO - app.core.security - [Redis] AOF persistence enabled with appendfsync=everysec.
2025-07-17 02:33:57,709 - INFO - app.core.security - LOGIN: user_id=11, email=root9678@gmail.com, user_type=live, time=2025-07-17T09:33:57.709611
2025-07-17 02:42:10,948 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T09:42:10.948872
2025-07-17 02:47:35,526 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:02:48,754 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:02:48,759 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:05:52,278 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:06:14,306 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:06:14,310 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:07:24,308 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T10:07:24.308334
2025-07-17 03:07:24,341 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T10:07:24.339131
2025-07-17 03:07:35,904 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:07:35.904257
2025-07-17 03:09:16,291 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:11:52,109 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:11:52,112 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:13:11,161 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:13:11.161868
2025-07-17 03:13:16,217 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T10:13:16.217145
2025-07-17 03:14:54,114 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:14:56,363 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:14:56,365 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:16:14,644 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T10:16:14.644516
2025-07-17 03:16:20,451 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:16:20.451912
2025-07-17 03:18:28,223 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:18:30,583 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:18:30,584 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:19:33,671 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:19:35,632 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:19:35,634 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:19:56,442 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:19:56.441950
2025-07-17 03:19:58,641 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:19:58.641769
2025-07-17 03:21:07,342 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:21:09,928 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:21:09,929 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:21:12,759 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:21:12.759386
2025-07-17 03:21:17,237 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:21:17.237400
2025-07-17 03:22:00,583 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T10:22:00.583498
2025-07-17 03:22:07,033 - INFO - app.core.security - LOGIN: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-17T10:22:07.033757
2025-07-17 03:22:41,960 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:29:07,235 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:29:07,236 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:31:08,920 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:31:11,372 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:31:11,373 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:31:43,347 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:31:45,860 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:31:45,862 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:33:17,278 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 03:37:52,570 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 03:37:52,571 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 03:38:22,161 - INFO - app.core.security - LOGOUT: user_id=12, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-17T10:38:22.160997
2025-07-17 03:38:28,971 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T10:38:28.971686
2025-07-17 03:41:10,726 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:07:20,065 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:07:20,070 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:08:43,832 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-17 04:08:43,927 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-17 04:09:10,382 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:09:40,796 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:09:40,799 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:09:44,099 - INFO - app.core.security - LOGOUT: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T11:09:44.098971
2025-07-17 04:09:54,623 - INFO - app.core.security - LOGIN: user_id=11, email=root9678@gmail.com, user_type=live, time=2025-07-17T11:09:54.623451
2025-07-17 04:10:35,297 - INFO - app.core.security - LOGOUT: user_id=11, email=root9678@gmail.com, user_type=live, time=2025-07-17T11:10:35.297652
2025-07-17 04:10:44,663 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T11:10:44.663829
2025-07-17 04:12:00,626 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:19:13,743 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:19:13,745 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:24:55,696 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-17T11:24:55.696562
2025-07-17 04:25:14,318 - INFO - app.core.security - LOGIN: user_id=9, email=kodideladinesh123@gmail.com, user_type=live, time=2025-07-17T11:25:14.318626
2025-07-17 04:27:58,810 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:28:45,067 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:28:45,069 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:37:31,540 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:41:23,716 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:41:23,718 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:41:37,579 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:41:39,838 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:41:39,839 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:47:05,256 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:47:07,601 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:47:07,603 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:49:32,205 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:53:56,002 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:53:56,003 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:56:20,649 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:57:04,929 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:57:04,931 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 04:57:23,220 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-17 04:58:15,337 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-17 04:58:15,338 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-17 05:04:10,148 - INFO - app.core.security - [Redis] Connection closed successfully.
