2025-07-22 03:19:55,117 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:19:55,118 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:21:25,287 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:21:53,547 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:21:53,549 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:23:58,985 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:28:32,205 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:28:32,207 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:30:31,842 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-22 03:30:31,938 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-22 03:30:41,089 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-22T10:30:41.089650
2025-07-22 03:30:49,033 - INFO - app.core.security - LOGIN: user_id=25, email=huttonsgroups90@gmail.com, user_type=live, time=2025-07-22T10:30:49.033293
2025-07-22 03:31:46,041 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:40:10,230 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:40:10,233 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:40:18,138 - INFO - app.core.security - LOGOUT: user_id=25, email=huttonsgroups90@gmail.com, user_type=live, time=2025-07-22T10:40:18.138574
2025-07-22 03:40:24,606 - INFO - app.core.security - LOGIN: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-22T10:40:24.606644
2025-07-22 03:42:36,131 - INFO - app.core.security - [Redis] Connection closed successfully.
